# Generated by Django 2.0.6 on 2018-06-29 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_auto_20180628_1703'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='departments.Position'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CV', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
