# Generated by Django 2.0.6 on 2018-06-29 03:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20180627_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='departments.Position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='vacancies.Vacancy'),
        ),
    ]
