# Generated by Django 2.0.6 on 2018-07-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20180630_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('last_name',), 'verbose_name_plural': 'candidates'},
        ),
    ]
