# Generated by Django 2.0.6 on 2018-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_auto_20180703_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('0', 'НЕ РАССМОТРЕНО'), ('1', 'РАССМОТРЕНО'), ('2', 'ПОДХОДИТ'), ('3', 'НЕ ПОДХОДИТ'), ('4', 'ОТПРАВЛЕН ТЕСТ'), ('5', 'ПРИГЛАШЕН НА ИНТЕРВЬЮ'), ('6', 'ИНТЕРВЬЮ ПРОВЕДЕНО'), ('7', 'ШТАТ'), ('8', 'РЕЗЕРВ'), ('9', 'СТАЖЕР'), ('10', 'НЕ ПРОШЕЛ ИНТЕРВЬЮ')], default=0, max_length=100),
        ),
    ]
