# Generated by Django 2.0.6 on 2018-07-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_auto_20180710_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('NOT_REVIEWED', 'На рассмотрений'), ('REVIEWED', 'Рассмотрено'), ('SATISFYING', 'Подходит'), ('NOT_SATISFYING', 'Не подходит'), ('TEST_SENT', 'Отправлен на тест'), ('INVITED_TO_INTERVIEW', 'Приглашен на интервью'), ('INTERVIEWS_CONDUCTED', 'Интервью проведено'), ('CURRENT_EMPLOYEE', 'Штат'), ('IN_RESERVE', 'Резерв'), ('INTERN', 'Стажер'), ('FAILED_INTERVIEW', 'Не прошел интервью')], default=0, max_length=100),
        ),
    ]
