# Generated by Django 2.0.6 on 2018-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('candidates', '0008_auto_20180710_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
