# Generated by Django 2.0.6 on 2018-07-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20180713_1154'),
        ('candidates', '0009_auto_20180712_1131'),
    ]

    operations = [
    ]
