# Generated by Django 2.0.6 on 2018-07-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_merge_20180713_1628'),
        ('candidates', '0009_auto_20180713_1002'),
    ]

    operations = [
    ]
