# Generated by Django 2.0.6 on 2018-07-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_auto_20180716_1729'),
        ('candidates', '0011_merge_20180716_1806'),
    ]

    operations = [
    ]
