# Generated by Django 2.0.6 on 2018-06-27 06:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('hh_payment_type', models.CharField(choices=[('PR', 'premium'), ('ST+', 'standard+'), ('ST', 'standard'), ('FR', 'free')], default='FR', max_length=3)),
                ('work_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=15)),
                ('experience', models.CharField(choices=[('0', 'No-experience'), ('1-3', '1-3 years'), ('3-6', '3-6 years'), ('6+', '6 or more')], default='0', max_length=3)),
                ('working_hours', models.CharField(choices=[('FT', 'full-time-day'), ('RS', 'rotation_shift'), ('FT', 'flexible-time'), ('RJ', 'remote-job'), ('SF', 'special-shift-day')], default='FT', max_length=2)),
                ('employment_patterns', models.CharField(choices=[('FT', 'full-time'), ('PT', 'part-time'), ('TMP', 'project/temporary'), ('VOL', 'volunteer'), ('INT', 'internship')], default='FT', max_length=3)),
                ('salary_min', models.FloatField()),
                ('salary_max', models.FloatField()),
                ('image_link', models.URLField()),
                ('posts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), size=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
