# Generated by Django 2.0.6 on 2018-06-28 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_hours',
            field=models.CharField(choices=[('FT', 'full-time-day'), ('RS', 'rotation_shift'), ('FLT', 'flexible-time'), ('RJ', 'remote-job'), ('SF', 'special-shift-day')], default='FLT', max_length=3),
        ),
    ]
