# Generated by Django 2.0.6 on 2018-06-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0003_auto_20180630_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='last_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
