# Generated by Django 2.0.6 on 2018-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0004_vacancy_last_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unpublished'), (1, 'Published')], default=0),
        ),
    ]
