# Generated by Django 2.0.6 on 2018-06-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0005_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
