# Generated by Django 2.0.6 on 2018-07-06 10:22

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20180703_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
