# Generated by Django 2.0.6 on 2018-07-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20180703_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'vacancies'},
        ),
    ]
