# Generated by Django 2.0.6 on 2018-07-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20180706_1453'),
        ('vacancies', '0010_auto_20180706_1622'),
    ]

    operations = [
    ]
