# Generated by Django 2.0.6 on 2018-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_merge_20180706_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
