# Generated by Django 2.0.6 on 2018-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20180706_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.IntegerField(choices=[(0, 'Полный рабочий день'), (1, 'Не полный рабочий день'), (2, 'Проект/временно'), (3, 'Волонтерство'), (4, 'Стажировка')], default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.IntegerField(choices=[(0, 'Без опыта'), (1, '1-3 лет'), (2, '3-6 лет'), (3, '6 лет и более')], default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_hours',
            field=models.IntegerField(choices=[(0, 'Полный рабочий день'), (1, 'Гибкий график'), (2, 'Удаленная работа')], default=0),
        ),
    ]
