# Generated by Django 2.0.6 on 2018-07-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_auto_20180709_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='status',
        ),
    ]
