# Generated by Django 2.0.6 on 2018-07-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_auto_20180709_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='experience',
        ),
    ]
