# Generated by Django 2.0.6 on 2018-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_vacancy_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='working_hours',
            field=models.CharField(choices=[('FULL_TIME', 'Полный рабочий день'), ('PART_TIME', 'Гибкий график'), ('REMOTE_JOB', 'Удаленная работа')], default=0, max_length=10),
        ),
    ]
