# Generated by Django 2.0.6 on 2018-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_auto_20180710_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='diesel',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='jobkg',
        ),
        migrations.AddField(
            model_name='publication',
            name='diesel_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='diesel_url',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='facebook_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='jobkg_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='jobkg_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
    ]
