# Generated by Django 2.0.6 on 2018-07-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_auto_20180713_1154'),
        ('vacancies', '0020_auto_20180711_1817'),
    ]

    operations = [
    ]
