# Generated by Django 2.0.6 on 2018-07-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0021_merge_20180713_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='created',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='diesel_exist',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='diesel_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='jobkg_exist',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='jobkg_url',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='diesel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='jobkg',
            field=models.BooleanField(default=False),
        ),
    ]
