# Generated by Django 2.0.6 on 2018-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_auto_20180716_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_service',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
