# Generated by Django 2.0.6 on 2018-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0024_publication_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
