version: '3'

services:
  app:
    build:
      context: .
    image: nest
    container_name: js_main
    environment:
      PORT: 3000
      DB_USERNAME: root
      DB_PASSWORD: root
      DATABASE_URL: postgres://root:root@postgres_js:5432/test7
    ports:
      - 9898:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: /bin/sh -c "sleep 5 && npm start"

  db:
    image: postgres:alpine
    restart: always
    container_name: postgres_js
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test7