# Generated by Django 2.0.6 on 2018-06-26 12:04

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[apps.users.validators.email_validator]),
        ),
    ]
