# Generated by Django 2.0.6 on 2018-07-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
