# Generated by Django 2.0.6 on 2018-06-29 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20180628_1148'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='departments.Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requirements',
            field=models.ManyToManyField(related_name='requests', to='departments.Requirement'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(default='-1'),
        ),
    ]
