# Generated by Django 2.0.6 on 2018-06-30 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20180628_1703'),
        ('requests', '0002_auto_20180627_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requirements',
            field=models.ManyToManyField(related_name='requests', to='departments.Requirement'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='departments.Position'),
        ),
    ]
