# Generated by Django 2.0.6 on 2018-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20180630_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
