# Generated by Django 2.0.6 on 2018-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20180710_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('0', 'НЕ РАССМОТРЕНО'), ('1', 'УТВЕРЖДЕНО'), ('2', 'ОТКЛОНЕНО')], default=0, max_length=100),
        ),
    ]
