# Generated by Django 2.0.6 on 2018-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20180710_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('NOT_REVIEWED', 'Не рассмотрено'), ('APPROVED', 'Утверждено'), ('DECLINED', 'Отклонено')], default=0, max_length=100),
        ),
    ]
