# Generated by Django 2.0.6 on 2018-07-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20180710_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_vacancy_created',
            field=models.BooleanField(default=False),
        ),
    ]
