# Generated by Django 2.0.6 on 2018-07-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_request_request_vacancy_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_vacancy_created',
            new_name='is_vacancy_created',
        ),
    ]
