# Generated by Django 2.0.6 on 2018-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_auto_20180716_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('NOT_REVIEWED', 'Не рассмотрено'), ('APPROVED', 'Утверждено'), ('DECLINED', 'Отклонено')], default='NOT_REVIEWED', max_length=100),
        ),
    ]
