# Generated by Django 2.0.6 on 2018-06-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.Candidate')),
            ],
        ),
    ]
