# Generated by Django 2.0.6 on 2018-06-29 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0002_interview_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.IntegerField(choices=[(0, 'Предстоит'), (1, 'Прошло'), (2, 'Отменено')], default=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='requests.Request'),
        ),
    ]
