# Generated by Django 2.0.6 on 2018-06-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20180629_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='request',
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='candidates.Candidate'),
        ),
    ]
