# Generated by Django 2.0.6 on 2018-06-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20180628_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='reviewers',
            new_name='interviewers',
        ),
    ]
