# Generated by Django 2.0.6 on 2018-07-03 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20180628_1703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0003_auto_20180629_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='interviews.Criteria')),
            ],
            options={
                'default_related_name': 'evaluations',
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewers',
        ),
        migrations.AddField(
            model_name='interviewer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviewers', to='interviews.Interview'),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='interviews.Interviewer'),
        ),
    ]
