# Generated by Django 2.0.6 on 2018-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20180703_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('0', 'ПРЕДСТОИТ'), ('1', 'ПРОШЛО'), ('2', 'ОТМЕНЕНО')], default=0, max_length=100),
        ),
    ]
