# Generated by Django 2.0.6 on 2018-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20180710_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('TO_BE_CONDUCTED', 'Предстоит'), ('CONDUCTED', 'Прошло'), ('CANCELLED', 'Отменено')], default=0, max_length=100),
        ),
    ]
