# Generated by Django 2.0.6 on 2018-07-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20180710_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date',
        ),
        migrations.AddField(
            model_name='interview',
            name='begin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='interview',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
