# Generated by Django 2.0.6 on 2018-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20180710_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('TO_BE_CONDUCTED', 'Предстоит'), ('CONDUCTED', 'Прошло'), ('CANCELLED', 'Отменено')], default='TO_BE_CONDUCTED', max_length=100),
        ),
    ]
