# Generated by Django 2.0.6 on 2018-07-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_auto_20180713_1002'),
        ('interviews', '0007_auto_20180716_1729'),
    ]

    operations = [
    ]
