# Generated by Django 2.0.6 on 2018-07-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_merge_20180717_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='event',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='begin_time',
            field=models.DateTimeField(),
        ),
    ]
