# Generated by Django 2.0.6 on 2018-06-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='departments.Department'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='departments.Department'),
        ),
    ]
