# Generated by Django 2.0.6 on 2018-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20180628_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('0', 'ОБЯЗАТЕЛЬНЫЕ'), ('1', 'ОПЦИОНАЛЬНЫЕ'), ('2', 'ОБЩИЕ'), ('3', 'НАВЫКИ')], default=0, max_length=100),
        ),
    ]
