# Generated by Django 2.0.6 on 2018-07-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20180711_0950'),
        ('departments', '0003_department_protected'),
    ]

    operations = [
    ]
