# Generated by Django 2.0.6 on 2018-07-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_merge_20180711_1221'),
        ('departments', '0006_merge_20180711_1229'),
    ]

    operations = [
    ]
