# Generated by Django 2.0.6 on 2018-07-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_merge_20180711_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='protected',
        ),
    ]
