# Generated by Django 2.0.6 on 2018-07-13 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0008_remove_department_protected'),
        ('departments', '0007_merge_20180711_1318'),
    ]

    operations = [
    ]
