# Generated by Django 2.0.6 on 2018-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_merge_20180713_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('REQUIRED', 'Обязательные'), ('OPTIONAL', 'Опциональные'), ('GENERAL', 'Общие')], default='REQUIRED', max_length=100),
        ),
    ]
