version: '2'

services:
  postgres:
    container_name: db
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    env_file:
      - .env

  web:
    restart: always
    build: .
    container_name: django
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
        bash -c "
        python wait_for_pg.py
        && python manage.py migrate
        && python manage.py collectstatic --noinput
        && python manage.py loaddata apps/fixtures/*
        && gunicorn -w 3 -b 0.0.0.0:8000 wsgi"
    volumes:
      - ./static:/code/static

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    links:
      - web:web
    depends_on:
      - web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
