# Generated by Django 2.0.6 on 2018-06-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20180627_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteriaRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.Criteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.Evaluation')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='feedback',
            field=models.ManyToManyField(through='evaluations.EvaluationCriteriaRelationship', to='evaluations.Criteria'),
        ),
    ]
