# Generated by Django 2.0.6 on 2018-06-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_auto_20180629_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='feedback',
            new_name='feedbacks',
        ),
    ]
